### ISSUE TITLE
Add `--rebase <pull request number>` option

### ISSUE THREAD

**Issue by sqren** [sqren/backport#117]
It should be easier to rebase PRs than it is today. 

Usage:
```
backport --rebase 15
```

Above command should attempt to rebase the head branch (`head.ref`) with the base branch (`base.ref`) for pull request number 15 - `upstream` should be read from `.backportrc.json` or passed in as CLI arg.

**Comment by spalger** [comment]
My two cents: I find that rebasing is generally more likely to have issues than simply pulling the base branch into a PR, so I'd ask that do an `--update` flag or something that will pull the latest from the base branch into the PR as a merge commit.

Something like:

```
git checkout {backportBranch}
git fetch origin {backportBranch}
git reset --hard origin/{backportBranch}
git pull origin {baseBranch} # pause here on conflict, git commit to resolve
git push origin {backportBranch}
```

**Comment by sqren** [comment]
Thanks for the feedback @spalger! Good point about using merge instead of rebase.

**Comment by sqren** [comment]
Closing since this is better solved by other tools.
