### ISSUE TITLE
Add ability to define custom Github URL

### ISSUE THREAD

**Issue by cjskillingstad** [sqren/backport#127]
- Right now the Github API Urls are hard coded for public Github. 
- It would be nice to be able to define a custom Github API Url for consumers using Github Enterprise.

**Comment by sqren** [comment]
Afaict `github.com` is hardcoded in calls to Github's API and in the git url.

**Calls to Github's API**
https://github.com/sqren/backport/blob/493aefbdee393a05ac3e22e9aceea127f1637de5/src/services/github.ts#L46-L49

Calls to the API are prefixed with `https://api.github.com/`. Would it be sufficient to just being able to replace the hostname part: `https://api.${githubHost}/` where `githubHost` defaults to `github.com` ?

**Git url**
https://github.com/sqren/backport/blob/fce7a4f4f3737cd63214813749398de8fe4415fe/src/services/git.ts#L42-L52

The git remote url currently looks like: `https://${accessToken}@github.com/${owner}/${repoName}.git`. Would this be sufficient:
`https://${accessToken}@${githubHost}/${owner}/${repoName}.git`?

**Comment by cjskillingstad** [comment]
@sqren This looks like exactly what I was thinking. More than happy to submit a PR

**Comment by sqren** [comment]
PRs are very welcome.

**Comment by sqren** [comment]
Resolved in https://github.com/sqren/backport/pull/129
