### ISSUE TITLE
Automatically resolve conflicts in yarn.lock

### ISSUE THREAD

**Issue by spalger** [sqren/backport#136]
It could be nice if backport automatically handled conflicts in `yarn.lock` files by running `yarn` (or a custom command like `yarn kbn bootstrap`) and then `git commit --no-edit` when  it exits successfully.

**Comment by sqren** [comment]
`backport` being a useful outside the realm of javascript I'm hesitant to implement something language specific like this.

For a while I've been thinking about changing the project config (`.backportrc.json`) from json to js. This would allow users to implement pre- and post-backport hooks.

Something like this could then be implemented:
```js
module.exports = {
  upstream: 'elastic/kibana',
  onConflict: async (files) => {
    if(files.includes('yarn.lock')) {
      return exec('yarn kbn bootstrap');
    }
  }
}
```

What do you think?

**Comment by spalger** [comment]
I'm not opposed, but would only want to handle automatic conflict resolution when the files were exactly just `yarn.lock`, but that happens less and less these days (in my experience) so I don't see it as particularly valuable.

**Comment by sqren** [comment]
> but that happens less and less these days (in my experience) so I don't see it as particularly valuable.

In that case, do you think this issue should be closed?
