### ISSUE TITLE
[Enhancement] Prevent accidental push from the backport repo

### ISSUE THREAD

**Issue by tsullivan** [sqren/backport#143]
Currently, backport clones the tracking repo under the remote name `origin` and the fork repo under the Github username of the user. In many dev environments, `origin` is used as the remote name for the user's fork.

[Based on the number of backport branches in Kibana](https://github.com/elastic/kibana/branches/all?utf8=%E2%9C%93&query=backport%2F), it looks like developers are accidentally doing the equivalent of `git push origin <branchname>`, possibly while working in the tool's private repo to resolve merge conflicts.

I like this suggestion from @timroes: 
> The backport tool should create a pre-push hook in that backport repo, that will prevent pushing if a specific environment variable isn't set (that it sets when itself pushes) and then just prints a warning: Don't push manually here, just follow instructions of the backport tool please

**Comment by sqren** [comment]
This is a super good point. After running into this a couple of times myself I added a fix recently. 

https://github.com/sqren/backport/blob/4f63c536bedd02292a5d9eb922e254dd14b38892/src/steps/maybeSetupRepo.ts#L35-L38

It will delete the `origin` remote and create a remote with the name of the organization (eg `elastic`) and the user (eg `timroes`). So `git push origin master` should not even be possible anymore.

I've opened a PR to update Kibana's version of backport: https://github.com/elastic/kibana/pull/43405
