### ISSUE TITLE
Allow commits with multiple parents

### ISSUE THREAD

**Issue by brianmcgue** [sqren/backport#150]
## Issue
Some folks are fans of the ol' squash-and-merge, which makes backporting easy since it's only one commit. For those who aren't, a similar way to do this is backporting the merge commit itself. Since merge commits have multiple parents, the `cherry-pick` phase fails. In order to `cherry-pick` correctly, one would need to use the [`--mainline`, `-m`](https://git-scm.com/docs/git-cherry-pick#Documentation/git-cherry-pick.txt--mparent-number) flag to specify which parent commit to use for the mainline or base branch. In most cases, this is the first parent: `git cherry-pick -m 1 <sha>`, but it would be nice to allow a user to specify that option.

## Proposal
Add a `--mainline` flag to allow backporting commits with multiple parents, such as merge commits.

## Considerations for implementation
Could use `1` as the default since it's the most common case and will work even with commits with only one parent. There's also an argument to be made that `null` should be the default which would allow `git cherry-pick` to fail like it currently does unless the user specifies the option.

**Comment by sqren** [comment]
Thanks for creating this! I'm by no means a git expert so my understanding of the mainline argument is limited. After reading up on it, it's still not clear to me, whether it'll be obvious to me in the situation which parent I should choose. What will it look like if users choose the wrong parent?
Would it perhaps be easier simply to pick the original commits instead of the merge commit?

Because this issue is so well-spec'd out it should be pretty easy to implement. I've started adding integration tests that performs the actual git operations which would be nice for this use case but it could make the feature a lot more time consuming to add - so I might just stick to unit tests.

**Comment by brianmcgue** [comment]
Sorry for taking so long here.

> What will it look like if users choose the wrong parent?

I wouldn't consider myself a git expert by any means, but after playing around with a few test branches and `git cherry-pick`, my understanding is that after merging, the parents are ordered as 1: base branch, 2: feature branch. So `--mainline=1` will refer to the master/versioned branch, and `--mainline=2` will refer to the feature branch. If you were to choose the wrong parent, it would assume the "base" branch is the feature branch and then apply all of the changes of the master/versioned branch in a single commit to the backport branch, which would not be great.

> Would it perhaps be easier simply to pick the original commits instead of the merge commit?

This can definitely be solved by selecting multiple commits. Sometimes there are a lot of commits though and it's easier to just select one (this may be my fault for allowing PRs with 20-40+ commits). If you want to close out this issue with the solution being "select all of the commits from the original PR", I think that's fair.

I _believe_ the `pullNumber` CLI argument uses the merge commit as well, so won't that fail during the `cherry-pick`ing stage, too? If yes, something like `-m 1` may solve it in most cases.

**Comment by sqren** [comment]
> I believe the pullNumber CLI argument uses the merge commit as well, so won't that fail during the cherry-picking stage, too? If yes, something like -m 1 may solve it in most cases.
@brianmcgue 

Good point and I really would like a solution for this. `-m` is doable but still requires the user to know about this. Oftentimes I can imagine the user will just select a commit and expect backport to work - regardless if it's a merge commit or not.

What I'm thinking is, that if it's possible programmatically to determine that a commit is a merge commit, and then retrieve all the commits that were part of the merge.

I played around with this a bit, and something like this seems to work:
```
git --no-pager log 14888de^..14888de --format="%Bsha:%H ___END_OF_COMMIT___"
```

`14888de` is the merge commit, and the command will list all commits that were part of the merge.

Response:
```
Merge pull request #7225 from ruflin/index-recovery

Add basic index recovery metricsetsha:14888de8341b24039642f5423382b3969d35fe14 ___END_OF_COMMIT___
remove info as not used yet
sha:0f843662b31ed1f5dbc6ca2319905ffe270bbb64 ___END_OF_COMMIT___
rebase
sha:3b2b3317313a9a109269798b6b84490732c088cb ___END_OF_COMMIT___
skip mapping errors
sha:e04a187c4d5651727783f07f960b23cde10f3c5d ___END_OF_COMMIT___
update generated file
sha:f23eb14957ae08eea8f536aa9240e22e4d103ac1 ___END_OF_COMMIT___
remove template part
sha:988b562d037ece7bb55f33325800cfefa95c2c1c ___END_OF_COMMIT___
improve testing
sha:cc9b504cef841e02504992919e3daf57f5d234dc ___END_OF_COMMIT___
Add basic index recovery metricset

Add basic metricset for index recovery. By default only data about indices is fetched that are currently recovering.

Further changes:

* Fix `NO_COMPOSE` flag for Golang integration tests
* Clean up elasticsearch.GetInfo to also use `fetchPath` function
* Enhance testing to also support settings metricset configs.
sha:89da914fc42a36856a6dfecaafe6b27d9f59e7f9 ___END_OF_COMMIT___
```

**Comment by brianmcgue** [comment]
It does feel magical. Whether it's too magical is a good question. Maybe you can just prompt the user asking if that's ok or not? Though, it seems if the user were to use the `pullNumber` feature, they would understand it's a merge commit, and wouldn't need to confirm anything.

Overall, if it works, it seems useful to me.

**Comment by sqren** [comment]
Hey @brianmcgue 

sorry for the long wait. I've finally gotten around to look into this. I've created a PR that adds the mainline option: https://github.com/sqren/backport/pull/179

It's released as a beta that you can install like:

```
npm install backport@5.1.6-beta.1
```
