### ISSUE TITLE
Fails to backport if a branch named "backport" exists on remote

### ISSUE THREAD

**Issue by watson** [sqren/backport#155]
If you already have a branch named `backport` in the remote repo, the backport tool fill fail to make the backport PR.

I think the issue is that all backport PR's live in branches that starts with `backport/...`. I think the technical reason for the issue is that if you make a branch named `foo` this is just a file on disk stored at `.git/refs/heads/foo`. But if you make a branch named `foo/bar`, git will attempt to store it on disk at `.git/refs/heads/foo/bar`. But if there's already a file named `foo` there, it can't also create a directory named `foo` - hence why backport fails if there's a branch named `backport`.

**Comment by sqren** [comment]
Thanks @watson. I'll add a check for this so the user is at least warned. Super bizarre bug, never considered this 😱

**Comment by domenkozar** [comment]
Erroring out the action in case this bug is hit would help notice the problem.
