### ISSUE TITLE
Cannot read property 'target' of null

### ISSUE THREAD

**Issue by ronkorving** [sqren/backport#158]
I've probably misconfigured something, but when I simply run `backport --verbose` it fails with:

```
✖ Loading commits...
TypeError: Cannot read property 'target' of null
    at Object.fetchCommitsByAuthor (/Users/rkorving/Projects/redacted/node_modules/backport/dist/services/github/fetchCommitsByAuthor.js:95:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```
which translates to https://github.com/sqren/backport/blob/2a100ccfe1c339ead0f3c985e920e19bcd4d11f3/src/services/github/fetchCommitsByAuthor.ts#L108

When I look in the verbose log, the last steps I see are:

```
2019-10-08T07:56:48.850Z verbose: {
  "repoOwner": "redacted-but-correct",
  "repoName": "redacted-but-correct",
  "commitsCount": 10,
  "authorId": "redacted-but-some-correct-looking-hash",
  "historyPath": null
}
2019-10-08T07:56:49.303Z verbose: {
  "data": {
    "repository": {
      "ref": null
    }
  }
}
```

I use github.com, a private repo, and I know I have commits in its history.
I enabled these scopes when creating a token for it:

![image](https://user-images.githubusercontent.com/631240/66378166-e3360500-e9ed-11e9-9763-0b952d669a39.png)

My project's `.backportrc.json` file:

```json
{
  "upstream": "myorg/myrepo",
  "branches": ["v0-master"],
  "all": true,
  "fork": true,
  "multipleCommits": true,
  "multipleBranches": true,
  "labels": ["backport"]
}
```

(I've tried with `"all": false` as well, but same result)

Backport v4.7.3.

**Comment by sqren** [comment]
Hi @ronkorving,

Thanks for making me aware of this.
I would love to be able to reproduce this scenario. Thinking through it, I don't understand how it can occur. Before this there are a couple of checks:
 - does the repo exist
 - is the access token valid
 - does the access token have the required scopes to access the repo

In this case all the three checks passed. Which makes me wonder why `res.repository.ref` is `null` 🤔 

A silly solution would be to check whether `res.repository.ref` is `null` and then return early. But that won't help you (the program won't crash but you won't be able to backport either).

Github has a GraphQL Explorer which lets you execute graphql requests: https://developer.github.com/v4/explorer/

Can you try running the following query:
```gql
query getCommitsByAuthorQuery($repoOwner: String!, $repoName: String!, $commitsCount: Int!, $authorId: ID, $historyPath: String) {
  repository(owner: $repoOwner, name: $repoName) {
    ref(qualifiedName: "master") {
      target {
        ... on Commit {
          history(first: $commitsCount, author: {id: $authorId}, path: $historyPath) {
            edges {
              node {
                oid
                message
                associatedPullRequests(first: 1) {
                  edges {
                    node {
                      repository{
                        owner {
                          login
                        }
                        name
                      }
                      number
                      timelineItems(last: 20, itemTypes: CROSS_REFERENCED_EVENT) {
                        edges {
                          node {
                            ... on CrossReferencedEvent {
                              source {
                                __typename
                                ... on PullRequest {
                                  state
                                  baseRefName
                                  commits(first: 20) {
                                    edges {
                                      node {
                                        commit {
                                          message
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

With these variables adjusted to your repo:
```json
{
  "repoOwner": "TODO",
  "repoName": "TODO",
  "commitsCount": 1
}
```

**Comment by ronkorving** [comment]
Assuming repoOwner is the GitHub account *name* (not some ID) owning the repo (in my case, the organization I work for), and the repoName being the *name* (not some ID) of the repo I'm interested in, the result is:

```
{
  "data": {
    "repository": {
      "ref": null
    }
  }
}
```

**Comment by ronkorving** [comment]
I just found out what it is! The query in `backport` assumes that my upstream branch is called `master`, but in our case it's not. We maintain multiple upstream versions, and we named our "master" branches after those versions, eg: `v0-master` and `v1-master`. If I change the query to look for `ref(qualifiedName: "v1-master") {`, `backport` starts working!

So the follow-up question is: are we using an incompatible branching model, or should `backport` be more configurable with regards to the upstream branch-names (plural)?

**Comment by sqren** [comment]
That's a great find! To paraphrase what you suggested:

The upstream branch should default to the default branch on github (in you case `v2-master`). Additionally it should be possible to manually set the upstream branch like
```
backport --upstream-branch v1-master
```

**Comment by ronkorving** [comment]
@sqren Sounds like we may be on the same page.

To rephrase my suggestion:

- if an upstream-branch is provided via configuration or CLI argument, it uses that
- else the interactive UI shows all upstream branches, and preselects the branch that is configured on GitHub as the default branch.

I think the GitHub default branch is useful for a good user experience, but you should be able to select a different one. So if you don't provide one, you need the ability to select a branch, I think. I'm not sure if that's already what you had in mind?

**Comment by ronkorving** [comment]
@sqren Shall we make a new issue for this?

**Comment by sqren** [comment]
@ronkorving I've started a PR in #160. You can try it out by installing the beta version

`yarn global add backport@beta` or `npm install -g backport@beta` 

LMK how it goes 🤞
