### ISSUE TITLE
Add the ability to forwardport a change

### ISSUE THREAD

**Issue by dakrone** [sqren/backport#172]
Occasionally I do work on a non-master branch and want to forwardport a PR to the master branch, however, even if I manually specify the SHA and branch:

```
~/es/elasticsearch (git) 0f312c8b  7.x [origin/7.x] (2 stashed)
» backport --sha 0f312c8b381fe19b69964f1ef677c9c46ed844b7 --branch master       
✖ Loading commit "0f312c8b"
No commit found on master with sha "0f312c8b381fe19b69964f1ef677c9c46ed844b7"
```

It appears to look for the sha on the `master` branch instead of 7.x.

It'd be great to be able to forwardport though!

**Comment by sqren** [comment]
Hey! 

This is already possible - but not very well documented, and it should probably work as you suggest.

By using the `[sourceBranch](https://github.com/sqren/backport/blob/master/docs/configuration.md#sourcebranch)` argument, you can specify to pick commits from a non-master branch:

The following will list commits on 7.x and backport the selected commit to master:
```
backport --sourceBranch 7.x --branch master
```

The following currently doesn't work, but I'll look into fixing it:

```
backport --sourceBranch 7.x --branch master --sha 0f312c8b381fe19b69964f1ef677c9c46ed844b7
```
