### ISSUE TITLE
Backport repo directory is no longer printed on conflicts.

### ISSUE THREAD

**Issue by spalger** [sqren/backport#193]
When I get conflicts in a backport I like to open a new VSCode window with the backport repo, so having the path to the repo printed was quite convenient. Now I need a little more precision to pull the repo path from the beginning of the file paths that are printed... It's a tiny QOL improvement, but it would be nice if the tool could print the path to the repo separately.

**Comment by sqren** [comment]
Makes sense. ICYMI: backport can open the the editor of your choice automatically when a conflict happens. 
Just add [`editor`](https://github.com/sqren/backport/blob/master/docs/configuration.md#editor) to your config file in `~/.backport/config.json`:

```json
{
  "username": "spalger",
  "accessToken": "abcdef",
  "editor": "code"
}
```

**Comment by spalger** [comment]
Hmm, not totally opposed but not a huge fan of things just popping up full screen

**Comment by sqren** [comment]
Whatever works for you :) I'll merge your other PR so people have both options (most people will probably not notice the `editor` option so good to have the path printed in the ui)
