### ISSUE TITLE
Possibilty to add label to original PR?

### ISSUE THREAD

**Issue by ariselseng** [sqren/backport#198]
Hi,
Thanks for --pr-filter param. It was really nice in our workflow!
Does it make sense to add a label (or remove a label) from the original PR?
Our devs adds the label "backport" to their PRs to master branch and then our ops guy run this to find PRs that needs backporting:
```backport --mainline --multiple --pr-filter "label:backport" --all --fork=false --branch release --upstream org/repo```

Is there anything we can add in our pr-filter or by another way to filter out those PRs that is already backported? Removing the "backport" label would be really nice.

**Comment by sqren** [comment]
It's not currently possible to remove labels again, but you can add labels to the "source" PR with [`--source-labels was-backported`](https://github.com/sqren/backport/blob/master/docs/configuration.md#sourceprlabels) and then filter it out with `--pr-filter "-label:was-backported"`:

```
backport --source-labels was-backported --mainline --multiple --pr-filter "label:backport -label:was-backported" --all --fork=false --branch release --upstream org/repo
```

If there are configuration options that rarely change you can put them in the `.backportrc.json` file:

```json
{
 "upstream": "org/repo",
  "sourceLabels": ["was-bcakported"],
  "multipleCommits": true,
  "multipleBranches": true,
  "all": true,
 "fork": false,
}
```

Then the command will be slightly simpler:
```
backport --mainline --pr-filter "label:backport -label:was-backported" --branch release
```

I noticed that `--pr-filter` and `--branch` are not available in `.backportrc.json`. Would you find it useful to hardcode those in a config file?

**Comment by ariselseng** [comment]
@sqren Thank you! That will work, yes :)
Wow, what a great tool :1st_place_medal: 
We are using a script to keep all parameters so I am not sure it will be very useful for our usecase, but it certainly is good for consistency. Again, thank you. You are doing an awesome job!

**Comment by sqren** [comment]
Thank you for the kind words! 🙇

**Comment by ariselseng** [comment]
@sqren I cannot get it to work. No label is added to the PR with --source-labels is-backported.
Does it need a special permission or something?

Here is the command I am using:
`backport --source-labels is-backported --mainline --multiple --pr-filter "label:backport -label:is-backported" --all --fork=false --branch release --upstream org/repo`

**Comment by sqren** [comment]
My bad! The docs are incorrect. You should use `--source-pr-labels`.
