### ISSUE TITLE
Use shallow clone to improve performance when cloning huge repos

### ISSUE THREAD

**Issue by sqren** [sqren/backport#201]
Cloning a big repository like Kibana can be very slow and take several minutes. To improve this it might make sense to shallow clone the repository
```
git clone https://github.com/elastic/kibana.git --depth=100
```

This will only fetch the most recent commit from the default branch and is thus much faster than cloning the entire history for all branches.

```
git fetch --update-head-ok origin 7.x:7.x --depth=1
```

**Comment by ankush** [comment]
Another option would be using the existing repository. E.g. wherever you're making a copy first do `git clone /home/user/folder..` and then you can change the origin. This way it's much faster to clone.

**Comment by sqren** [comment]
@ankush that's a great idea too 👍
