### ISSUE TITLE
pr-filter with label containing spaces

### ISSUE THREAD

**Issue by mbarto** [sqren/backport#202]
I am using --pr-filter "label:Backport Needed" and it doesn't seem to work.
Are spaces supported in filtering labels?

**Comment by sqren** [comment]
I think you can work around this by adding an extra pair of quotes:
```
 --pr-filter "label:'Backport Needed'" 
```

This is not specifically an issue with backport but how Github works: https://help.github.com/en/github/searching-for-information-on-github/understanding-the-search-syntax#use-quotation-marks-for-queries-with-whitespace

**Comment by mbarto** [comment]
Wonderful, it worked!
