### ISSUE TITLE
Support adding reviewers to the backport PR

### ISSUE THREAD

**Issue by mdelapenya** [sqren/backport#212]
Wdyt about adding that support in both the CLI and the configuration file?

**Comment by sqren** [comment]
Sure!  What do you think about `backport --reviewer mdelapenya`. And in the config file:
```json
{
  "reviewers": ["mdelapenya", "..."]
}
```

?

**Comment by mdelapenya** [comment]
Love it!
![image](https://media.giphy.com/media/42YlR8u9gV5Cw/giphy.gif)
