### ISSUE TITLE
--source-pr-labels is not working anymore, but --sourcePRLabels works

### ISSUE THREAD

**Issue by ariselseng** [sqren/backport#234]
Hello,
I recently updated backport and now the --source-pr-labels has no effect.
```shell
backport --mainline --source-pr-labels is-backported --multiple --pr-filter "label:backport -label:is-backported" --all --fork=false --branch release --upstream org/repo

**Comment by ariselseng** [comment]
I just tried with --source-pr-labels="is-backported" and then it worked. Does that make sense?

**Comment by ariselseng** [comment]
@sqren I tried again now with --source-pr-labels="is-backported" and it did not apply the label. Can you look into this?

**Comment by ariselseng** [comment]
After some digging I found out that --sourcePRLabels "is-backported" works, but not --source-pr-labels "is-backported".

**Comment by sqren** [comment]
Hey @ariselseng,
Sorry for the slow response and good job chasing down a workaround. I've found the problem and created a [PR](https://github.com/sqren/backport/pull/236) to fix this.
