### ISSUE TITLE
Customization of backported commit message

### ISSUE THREAD

**Issue by costin** [sqren/backport#243]
Would it be possible to customize the message of the cherry-picked commits?
Instead of `Backport of  ...` in the body, I'd like to copy the original commit description, adding a trailing:
`(cherry picked from commit xxxxx)`.

See https://github.com/elastic/elasticsearch/commit/443d30888edc2e9fe71700eebf79dcf3814b0f01 as an example.

Would it be possible to expose the original commit message and sha as variables to be used inside the description?

Thanks,

**Comment by sqren** [comment]
Good idea. I'll look into this!

**Comment by sqren** [comment]
Hey @costin 

I've finally gotten around to adding support for this. I completely understand if this is no longer on your radar but I have a [PR open](https://github.com/sqren/backport/pull/279) and I'd like your opinion on naming and whether this should be enabled by default.

**Context:**
Appending `(cherry picked from commit xxxxx)` is a feature of git and can be performed with the `-x` flag like: `git cherry-pick -x abc` 

My initial idea was to make this flag default to `false` (so it wouldn't append the reference) but I actually think it makes sense to have it in 99% of cases. People can always disable it - both on an ad-hoc basis and project-wide. 

Another question: what should the option be called? Git simply calls it `-x` and there's no longer, more descriptive option.
I initially called it `--cherrypick-ref` but I'm not totally sold on that.

If it's going to be enabled by default it should be negated like `backport --no-backport-ref`.

Any thoughts?
Thanks!

**Comment by costin** [comment]
Hi.
Glad to hear you're looking into this issue.
Looking at your comment and PR it looks like you're investigating only the trailing message ,`(cherrypick...)` and not reusing the original commit message. 
If possible please consider that as well in the future.

I like the cherry pick option and use it myself since it signals the intent and history even though it's sometimes redundant.
+1 from my side to include it by default.
-x is a bit obscure for me.
How about --add-cherrypick-message/commit/ref?

**Comment by sqren** [comment]
> Looking at your comment and PR it looks like you're investigating only the trailing message ,(cherrypick...) and not reusing the original commit message.

My intention is to use `git cherry-pick -x <sha>` which (to my knowledge) will use the existing commit message **and** append "(cherry picked from commit xxxxx)". 

So if the original commit message was "Foo", the backported commit message will be "Foo\n\n(cherry picked from commit xxxxx)"

Btw. this is specifically for the commit message for the backported commit, and not for configuring the pull request body (although the pull request body will contain a list of the backported commits). 

If I'm misunderstanding something please let me know! :)

> How about --add-cherrypick-message/commit/ref?

I like it 👍 And if it's enabled by default I might add `--omit-cherrypick-message` (or something like it).

**Comment by costin** [comment]
Thanks for clarifying! Sounds good to me.

> Btw. this is specifically for the commit message for the backported commit, and not for configuring the pull request body (the pull request body will list the original commits).

Isn't that going to create issues with Github? From what I can tell the PR body is used by GH for the commit message - at least that's been my experience (not sure if it's UI specific thing).

**Comment by sqren** [comment]
> Isn't that going to create issues with Github? From what I can tell the PR body is used by GH for the commit message - at least that's been my experience (not sure if it's UI specific thing).

I don't think that's a problem. According to [the docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#merge-message-for-a-squash-merge) Github will use the the commit message (and not the PR body) if there's only a single commit. If there are multiple commits the PR title, and the list of commit messages will be used. So in both cases the "cherrypick reference" will always be included
