### ISSUE TITLE
Incompatible with the latest git?

### ISSUE THREAD

**Issue by spalger** [sqren/backport#244]
We're getting reports that after upgrading git backport is no longer working... Unclear if I can reproduce as I'm afraid to upgrade and not have backport work anymore 😬.

RE https://github.com/elastic/kibana/issues/88310

**Comment by sqren** [comment]
Hey @spalger 

Thanks for opening this. I think this is a duplicate of https://github.com/sqren/backport/issues/233 which was closed in https://github.com/sqren/backport/pull/241 (released as 5.6.4). I updated the version in Kibana in https://github.com/elastic/kibana/pull/88428.

tldr: updating to 5.6.4 should fix it 🤞

**Comment by spalger** [comment]
Thank you!
