### ISSUE TITLE
Error backporting a PR with the Github action

### ISSUE THREAD

**Issue by mdelapenya** [sqren/backport#247]
I'm seeing this error in log

>⚠️  Ouch! An unknown error occured 😿
Error message: Command failed: git remote rm github-actions[bot]
error: No such remote: 'github-actions[bot]'

And the backport is not performed. Any guess?

**Comment by sqren** [comment]
Hey @mdelapenya !

Sorry for the slow response. I don't know if this is still relevant but can you try using the [backport action bundled with `kibana-github-actions`](https://github.com/elastic/kibana-github-actions/tree/main/backport)?

Thanks!

**Comment by sqren** [comment]
Closing this for now. Feel free to comment here or open a new issue.

**Comment by mdelapenya** [comment]
Hey, I fixed it in my own fork for the GH action: https://github.com/mdelapenya/backport-github-action/commits/master

**Comment by sqren** [comment]
Ahh cool! I wonder if some of those changes also would make sense for the kibana GH action.
