### ISSUE TITLE
Add `--config-file` to the CLI

### ISSUE THREAD

**Issue by tarekziade** [sqren/backport#265]
The `.backportrc.json` file name is hardcoded at https://github.com/sqren/backport/blob/b14d9778be41be8ccdbd0a936821b9e19549a095/src/options/config/projectConfig.ts#L5

which makes it impossible to provide another name.

My use case is to allow developers to run `backport` locally using a specific configuration, and use another configuration when the `backport` is done in the CI/CD.

surfacing a `--config-file` option that defaults to `.backportrc.json` will allow this.

Happy to contribute a patch if @sqren thinks that sounds good

**Comment by sqren** [comment]
I've been thinking about this myself but didn't get around to it. 
A PR is very welcome
