### ISSUE TITLE
Support configuring the location for ~/backport/repositories

### ISSUE THREAD

**Issue by sarod** [sqren/backport#269]
It would be useful to support configuring the location of temporary repositories folder especially when working with large repos.

**Comment by sqren** [comment]
Hey! Thanks for creating this issue. I've opened up a PR for adding support for this. This will make it possible to checkout the repo to a custom location on the fly eg `backport --dir my/custom/location`. The global config containing the `accessToken` will still be retrieved from `~/.backport/config.json` though. 

Sounds good to you?
