### ISSUE TITLE
Per project configuration

### ISSUE THREAD

**Issue by spalger** [sqren/backport#27]
The config file currently lives in `~/.backport`, which is fine, but it would be awesome if we could check-in the config for a project (like the repo location, branches, etc)

**Comment by sqren** [comment]
I imagine the config would look something like:

```json
{
    "name": "elastic/kibana",
    "versions": ["6.x", "6.1", "6.0"],
    "labels": ["backport"],
}
```

Is that what you had in mind? It will only be picked up, if `backport` command is run from inside the repo folder, eg `elastic/kibana/plugins`. What should happen if a project config is picked up, and the user-defined config also specifies branches for the same project? Should they be merged? And which should take precedence?

**Comment by spalger** [comment]
I would probably change the config resolution to function more like:

 1. look for a `.backportrc` file starting in cwd and walking up (using [find-up](https://github.com/sindresorhus/find-up) or something)
 1. if no `.backportrc` file is found, fail
 1. look for a `~/.backport/config.json` file
 1. if no `~/.backport/config.json` is found, create config file and fail

`~/.backport/config.json` should look like:
```json
{
  "accessToken": "...",
  "username": "..."
}
```

`.backportrc.json` should look like this:
```json
{
  "upstream": "elastic/kibana",
  "origin": "{username}/kibana",
  "own": true,
  "multiple": true,
  "versions": ["6.x", "6.0", "5.6", "5.5", "5.4"],
  "labels": ["backport"]
}
```

I don't think there's any reason the backport tool needs to support overrides or per-project config in the `~/.backport/config.json` file, if they want per-project configurations that should just add a `.backportrc` file to their project. They don't have to commit it if they are just trying things out.

**Comment by sqren** [comment]
That makes sense! I also prefer the naming you use, eg. `upstream`. 

A couple of thoughts:
 - Currently `origin` is derived from `upstream` (replaces "elastic" with _{username}_) - so is `origin` necessary to have explicitly?
 - `multiple` has been replaced with `multipleCommits` and `multipleVersions`. I feel it would be hard for all devs in a project to converge on the same settings. Eg. I always backport one commit at a time (`multipleCommits: false`) but backport to several versions (`multipleVersions: true`). Others might do it differently.

That's just my impression of how people work but it would be great if we can just have a single config, and users don't have to think.

**Comment by sqren** [comment]
Maybe `~/.backport/config.json` can override whatever project-specific settings we have, but by default `~/.backport/config.json` only contains:

```
{
  "accessToken": "...",
  "username": "..."
}
```
as you said. That way users actively have to override the project settings, if they really want to, but it'll Just Work for them if they don't.

**Comment by sqren** [comment]
> I don't think there's any reason the backport tool needs to support overrides or per-project config in the ~/.backport/config.json file, if they want per-project configurations that should just add a .backportrc file to their project

My thinking is: if I add `.backportrc` to Kibana, and someone doesn't like the settings, shouldn't they be able to change them for themselves?

**Comment by epixa** [comment]
Personally, I think if a project specifically wants certain configurations, individual users shouldn't be able to override them.  Otherwise we can't reliably ensure that our automation is doing what we need/want it to do.

**Comment by spalger** [comment]
@sqren I assume you're talking about options like `"own"` and `"multiple"`. I think it makes sense to limit those to CLI flags and maybe make them global (not per project) in `.backport/config.json`. 

I guess part of my design includes not specifying project-specific configuration in the `.backport/config.json` file because I'm not super fond of the way configs are mapped to the "current project". It currently tests that `basename(process.cwd()` matches the last path segment of `repositories[i].name`, which surprised me. By removing all project specific config from there we can remove that mapping and just rely on properly placed config files (which I think most users are used to).

**Comment by sqren** [comment]
> If I'm reading the implementation correctly it currently tests that basename(process.cwd() matches the last path segment of repositories[i].name, which surprised me

Yeah, we definitely want to get rid of that. That should also happen automatically with the addition of a `.backportrc.json`.

> I assume you're thinking about options like "own" and "multiple". I think it makes sense to limit those to CLI flags and maybe make them global (not per project) in .backport/config.json.

Yes, it was exactly those I meant. I'll try removing all the project specific stuff, and move it to a `.backportrc.json` - that's also more in line with other projects.

**Comment by sqren** [comment]
@spalger I just talked to @vanjacosic and he had a good point about backport labels. Currently his config looks like:

```json
{
  "repositories": [
    {
      "name": "elastic/kibana",
      "versions": ["6.x", "6.1"],
      "labels": ["apm", "backport"]
    }
  ]
}
```

As I understand your suggestion, he would only be able to add custom labels (like "apm") 
 - if `.backportrc.json` is not checked in (and thus is per user)
 - if he can override it from a user config.

Do you see any good ways to support this use-case?

**Comment by epixa** [comment]
As far as I know he's the only person doing this - is it necessary?  The backports link to a canonical issue that has the relevant feature/team labels on it.  The backport label itself is really just there for filtering and automation.

**Comment by spalger** [comment]
> "labels": ["apm", "backport"]

That's an interesting idea, and seems like a reasonable default, maybe the global config could accept an array of labels and apply those without filtering by project, or perhaps we could change the per-project overrides in the global config to be selected with a path of some sort rather than the current matching.

Something like this perhaps:
```json
{
  "overrides": [
    {
      // must point to the directory containing a .backportrc file
      "project": "~/dev/kibana",
      "labels": ["apm", "backport"]
    }
  ]
}
```

Alternatively, we could add `--labels apm,backport` support to the CLI (might already support it) and people could setup bash aliases for custom config

**Comment by sqren** [comment]
@spalger @epixa 
I ended up with a compromise, so the project config (`.backportrc.json`) behaves as described in https://github.com/sqren/backport/issues/27#issuecomment-348350190, but can be overridden by the global config (`.backport/config.json`). By default the global config will be empty, and only require `accessToken` and `username`, so most users will never override the project config - I see it as a hidden feature for power users.

There is an open PR https://github.com/sqren/backport/pull/29 and I've published a beta version that you can install if you want to try it out: `npm install backport@2.1.1-beta`

With the beta you can add the following `.backportrc.json` to the kibana repo:
```json
{
  "upstream": "elastic/kibana",
  "versions": ["6.x", "6.0", "5.6", "5.5", "5.4"],
  "labels": ["backport"]
}
```

**Comment by sqren** [comment]
Btw. I'm thinking about renaming "versions" to "branches", since that's really what they are. Any objections?

**Comment by sqren** [comment]
Closed by https://github.com/sqren/backport/pull/29
