### ISSUE TITLE
Use locally defined email for commits

### ISSUE THREAD

**Issue by sqren** [sqren/backport#270]
Currently the backport tool uses the globally defined email when for the backport commit. Instead it should use the locally defined email address.

The email address for the local repo can be retrieved with `git config user.email` and updated with `git config --local user.email john.doe@email.co`

**Comment by raubel** [comment]
Hi,
Why has this issue been closed?
I'd be interested in retrieving user email and username from local branch (or from the user's backport config file), because I don't want to define global git properties to define them.
Is that possible with the current version.

Today, I end up with this error:
```
remi > backport
? Select commit #506 (4c36bfb6)
? Select branch V5_3
✔ 100% Cloning repository (one-time operation)

Backporting to V5_3:
✔ Pulling latest changes
✖ Cherry-picking: story(API): optimize persist and mass update data request processing (#506)
Cherrypick failed:
Command failed: git cherry-pick -x 4c36bfb653a6b6ad040a3694599274ea62733b9f
Performing inexact rename detection: 100% (409500/409500), done.

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'remi@remi-example.(none)')
```
