### ISSUE TITLE
Allow for just a link instead of a `img.shields.io` image

### ISSUE THREAD

**Issue by pickypg** [sqren/backport#320]
https://github.com/sqren/backport/blob/c83e73a4db5fd84218bf72efa9a39ea8fd78bda8/src/lib/github/v3/createStatusComment.ts#L134

`img.shields.io` assumes a public repository. When using this for a private repository, it would be nice if I could provide a flag (for the GitHub action) to just provide a link to the PR.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/1501235/159376209-4ac69e00-4e8a-47c7-9860-a815cf52eeb7.png">

**Comment by sqren** [comment]
Hey @pickypg 

Thanks for making me aware of this. Instead of making this configurable I prefer to just disable the shields for private repos. WDYT of that?
