### ISSUE TITLE
Add support for dynamic `targetPRLabels`

### ISSUE THREAD

**Issue by jumaffre** [sqren/backport#391]
As far as I can see from the documentation and examples out there, the specified `targetPRLabels` is always static (typically set to `["backport"]`). However, in some cases, it would be useful to be able to specify a dynamic label to add to the backport PR, e.g. to include the major version of the branch this PR is backported to.

For example, based on the existing `branchLabelMapping`, `targetPRLabels` could become: `["$1-backport"]`.

Please let me know if this use case makes sense and whether `backport` already supports such functionality. [We've already been using this convention](https://github.com/microsoft/CCF/pulls?q=is%3Apr+is%3Aclosed+label%3A2.x-backport) when manually backporting PRs to release branches and would like to continue doing so when automatising this process.

**Comment by sqren** [comment]
This is a great idea. Using the regex placeholder (`$1`) is an interesting idea and it could definitely work. I can see this being a little confusing to users since `targetPRLabels` is not directly related to `branchLabelMapping`. 

I've been thinking about adding support for a js-based config file (in addition to the current json-based one).

```js
// .backportrc.js
module.exports = {
  targetPRLabels: (sourceCommit, targetBranch, sourcePRLabel) => {
    const match = sourceLabel.match(/(.*)-todo$/)?.[1];
    if (match) {
      return [match]
    }
  }
}
```

Do you have any preferences?

**Comment by jumaffre** [comment]
I agree that using `$1` in `targetPRLabels` is far removed from `branchLabelMapping`. On the other hand, we don't have a use case (yet?) for using a custom JS script, but that sounds like the best option in this case as it's extensible and opt-in only.

**Comment by sqren** [comment]
I've created a PR to support dynamic target labels like you suggested: https://github.com/sqren/backport/pull/400/files

**Comment by sqren** [comment]
@jumaffre Support for dynamic `targetPRLabels` was added in https://github.com/sqren/backport/pull/400 and released in v8.7.0.

I still haven't bumped the [github action](https://github.com/sqren/backport-github-action). If you want to try it out with a Github action, please specify `main` branch as version in the workflow file (`/.github/workflows/backport.yml`):

```
uses: sqren/backport-github-action@main
```

**Comment by jumaffre** [comment]
@sqren This is working as expected. Thank you very much for sorting this out so quickly. 

Separately to this, the following error occurred when I tried this new feature and tagged the same PR with two separate tags: https://github.com/microsoft/CCF/runs/7029861991?check_suite_focus=true. Could this be because our flow is a little different (we checkout the repository explicitly to avoid merge conflicts on a well-known file)?

**Comment by sqren** [comment]
> Separately to this, the following error occurred when I tried this new feature and tagged the same PR with two separate tags: https://github.com/microsoft/CCF/runs/7029861991?check_suite_focus=true. Could this be because our flow is a little different (we checkout the repository explicitly to avoid merge conflicts on a well-known file)?

Ouch, that looks bad. I don't know why multiple processes would run simultaneously and cause this. I'll try to see if I can reproduce.

**Comment by sqren** [comment]
@jumaffre I haven't been able to repro even when using [your workflow file](https://github.com/microsoft/CCF/blob/130319811fae846c2c4678b4f6c6cf36170fdd16/.github/workflows/backport.yml). Does the problem happen consistently for you or intermittently?
