### ISSUE TITLE
Explain configuration option: config-file

### ISSUE THREAD

**Issue by MstrDC** [sqren/backport#439]
How does the config-file configuration option work?

Setup:
Repo ABC:
- .github (protected folder via policy-bot)
  - .backportrc.json (1)
- .backportrc.json (0)

This doesnt work for me:
- .backportrc.json (0):
{
    "config-file": "/.github/"
}
- .backportrc.json (1):
Full setup.

What am I doing wrong here? I tried many different paths...

**Comment by sqren** [comment]
Config file is for specifying a path to the `.backportrc.json` if it's not in the root of the project.

My suggestion is to put `.backportrc.json` in the root, and then you can run backport without specifying `--config-file`. 

You can also place the config file anywhere you want, and then refer to it like:
```
backport --config-file /path/to/config/file
```

**Comment by MstrDC** [comment]
Thank you for your answer. So it is a CLI parameter only.
Because currently it is listed under config file options as well.
If you want, I can try to create a PR to update the documentation.

**Comment by sqren** [comment]
That would be great. i agree, it doesn't make sense under config file options.

**Comment by MstrDC** [comment]
Thank your for your quick response and action.
Closing this issue now.
