### ISSUE TITLE
Backport always performs a clone

### ISSUE THREAD

**Issue by MstrDC** [sqren/backport#440]
I noticed that backport always performs a full clone. Why is this? 
Why after the first clone, doesnt check backport if the data already exists and if so, performs a simple pull?
Is there a specific reason for this?

**Comment by sqren** [comment]
Hi @MstrDC 

If that's the case it's a bug. It should check for the presence of the repo in the backport folder (`~/.backport/`). If it doesn't exist it will clone the repo:

https://github.com/sqren/backport/blob/cb535301ba5f55f0c4f389d6ea977566797022f2/src/lib/setupRepo.ts#L16-L25

## Questions

1. What version of backport are you running?
2. Can you check the logs in `.backport/backport.debug.log`

Thanks!

**Comment by MstrDC** [comment]
@sqren ,
Thanks for your quick reponse!
- npx backport -v => 8.9.3
- I did check and the folder already exists under C:\\...~/.backport/repositories/MstrDC-codebase/....  
- npx backport command is run from X:\\repo
- See attached log file: [backport.debug.log](https://github.com/sqren/backport/files/9634979/backport.debug.log)

**Comment by sqren** [comment]
Cool. You have the latest version of the backport tool. This might be a problem specific to Window. I'm on a Mac but will try to find a Windows machine to reproduce.

**Comment by MstrDC** [comment]
@sqren ,
I can confirm that this is on Windows 10.
Looking at this piece of code, I believe a path.normalize needs to be added.
`async function getIsRepoCloned(options: ValidConfigOptions): Promise<boolean> {
  const repoPath = path.normalize(getRepoPath(options));
  const projectRoot = await getGitProjectRootPath(repoPath);
  return repoPath === projectRoot;
}`

Otherwise it is always false (debugger):
projectRoot: "C:/Users/MstrDC/.backport/repositories/backport-org/backport-demo"
repoPath: "C:\\Users\\MstrDC\\.backport\\repositories\\backport-org\\backport-demo"

So problem with back/forward slashes?

**Comment by sqren** [comment]
Thank you so much for diving into this. Much appreciated. Will take a look at the PR.

**Comment by MstrDC** [comment]
Thank your for your quick response and action.
Closing this issue now.
