### ISSUE TITLE
Support ssh keys with passphrase applied

### ISSUE THREAD

**Issue by legrego** [sqren/backport#55]
backport does not appear to support ssh keys that are protected by a passphrase. The process hangs indefinitely when trying to clone the repository. If I recreate my key without a passphrase applied, then the backport works perfectly.

I'm guessing that the git client is waiting for the passphrase to be entered via stdin, but backport doesn't expose/allow that to be entered via command line. It would be nice if we could enable this support, so users can protect their keys if they so choose.

#### System Config:
- OS: macOS High Sierra 10.13.3
- Git Client: 2.14.3 (Apple Git-98)

**Comment by sqren** [comment]
This is a good point. I was looking at ways to capture interaction while working on https://github.com/sqren/backport/issues/45 but didn't find any good way of doing it. 

I would like it if `backport` could maintain control of the flow, so a password prompt doesn't suddenly appear (it also messes with the loading spinners).
However, it seems like I can't simply capture the output from an interactive shell like `ssh` with Node's `child_process`, and I need to use something like [`pty.js`](https://github.com/chjj/pty.js) instead.

A workaround would be to [add your ssh key to the `ssh-agent`](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent)

I'll try to look into this soon-ish.

**Comment by legrego** [comment]
Great idea about using the ssh-agent. I completely forgot about that option. Thanks!

**Comment by sqren** [comment]
Good to hear the workaround solved it for now. Closing this for now in favor of https://github.com/sqren/backport/issues/56
